### ISSUE TITLE
建议增加任务栏小图标右键功能

### ISSUE THREAD

**Issue by charley008** [ChiyukiGana/Quickinput#2]
这样就可以右键任务栏小图标退出 等快捷操作，不需要每次点开程序界面 点一下红色按钮。

**Comment by ChiyukiGana** [comment]
好的，那我增加一个启用禁用和退出

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
From: charley008 ***@***.***>
Sent: Wednesday, January 3, 2024 11:38:00 AM
To: ChiyukiGana/Quickinput ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [ChiyukiGana/Quickinput] 建议增加任务栏小图标右键功能 (Issue #2)


这样就可以右键任务栏小图标退出 等快捷操作，不需要每次点开程序界面 点一下红色按钮。

―
