### ISSUE TITLE
2024-3-24版4k屏幕问题

### ISSUE THREAD

**Issue by charley008** [ChiyukiGana/Quickinput#8]
2024-3-24版本对4k屏支持不是很好，窗口很小
![屏幕截图 2024-03-24 101249](https://github.com/ChiyukiGana/Quickinput/assets/24822683/8efffe48-ff1b-4c96-a77e-c994b299c792)
![屏幕截图 2024-03-24 101743](https://github.com/ChiyukiGana/Quickinput/assets/24822683/1939db4e-3556-45ff-bfbe-7b246b5a6091)

**Comment by ChiyukiGana** [comment]
设置勾选禁用缩放了吗？

**Comment by charley008** [comment]
没有勾选禁用缩放。配置文件没改过，只替换了主程序
